apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runbear-worker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runbear-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "runbear-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "runbear-worker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "runbear-worker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: API_HOST
              value: {{ .Values.runbear.apiHost }}
            {{- if or .Values.runbear.apiSecret .Values.runbear.apiSecretExistingSecret }}
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "runbear-worker.apiSecretSecretName" . }}
                  key: api-secret
            {{- end }}
            - name: EXECUTOR_IMAGE
              value: "{{ .Values.runbear.executor.image.repository }}:{{ default .Chart.AppVersion .Values.runbear.executor.image.tag }}"
            - name: EXECUTOR_SERVICE_ACCOUNT_NAME
              value: {{ template "runbear-worker.executorServiceAccountName" . }}
            - name: EXECUTOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
