{{- if and .Values.runbear.executor.rbac.create (not .Values.runbear.executor.rbac.existingClusterRoleName) (not .Values.runbear.executor.rbac.useRole) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "runbear-worker.labels" . | nindent 4 }}
  name: {{ include "chart.fullname" . }}
{{- with .Values.runbear.executor.rbac.clusterRoleRules }}
rules: {{ toYaml . | nindent 2 -}}
{{- end }}
{{- end -}}
