{{- if .Values.runbear.executor.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.runbear.executor.serviceAccount.name }}
  labels:
    {{- include "runbear-worker.labels" . | nindent 4 }}
{{- end }}
