{{- if and .Values.runbear.executor.rbac.create .Values.runbear.executor.rbac.roleName -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "runbear-worker.executorServiceAccountName" . }}
  labels:
    {{- include "runbear-worker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "runbear-worker.executorRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "runbear-worker.executorServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
