{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "runbear-worker.serviceAccountName" . }}
  labels:
    {{- include "runbear-worker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "runbear-worker.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "runbear-worker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
