{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "runbear-worker.labels" . | nindent 4 }}
  name: {{ include "runbear-worker.roleName" . }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "pods/portforward"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end -}}
