{{- if and .Values.runbear.apiSecret (not .Values.runbear.apiSecretExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "runbear-worker.apiSecretSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runbear-worker.labels" . | nindent 4 }}
type: Opaque
data:
  api-secret: {{ .Values.runbear.apiSecret | b64enc | quote }}
{{- end }}
